apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-credit
  labels:
    app: ms-credit-deployment
spec:
  selector:
    matchLabels:
      app: ms-credit-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-credit-pod
    spec:
      containers:
        - name: ms-credit
          image: nicolassepulvedab/ms-credit-service
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_CREDITS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_CREDITS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_CREDITS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_CREDITS
            - name: CONFIG_SERVER_HOST
              value: "config-service-service"