apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-document
  labels:
    app: ms-document-deployment
spec:
  selector:
    matchLabels:
      app: ms-document-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-document-pod
    spec:
      containers:
        - name: ms-document
          image: nicolassepulvedab/ms-document-service
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_DOCUMENTS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_DOCUMENTS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_DOCUMENTS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_DOCUMENTS
            - name: CONFIG_SERVER_HOST
              value: "config-service-service"
            - name: EUREKA_HOST
              value: "eureka-service-service"
            - name: EUREKA_PORT
              value: "8761"
            - name: INSTANCE_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
