apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-evaluation
  labels:
    app: ms-evaluation-deployment
spec:
  selector:
    matchLabels:
      app: ms-evaluation-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-evaluation-pod
    spec:
      containers:
        - name: ms-evaluation
          image: nicolassepulvedab/ms-evaluation-service
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_EVALUATIONS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_EVALUATIONS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_EVALUATIONS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_EVALUATIONS
            - name: CONFIG_SERVER_HOST
              value: "config-service-service"
            - name: EUREKA_HOST
              value: "eureka-service-service"
            - name: EUREKA_PORT
              value: "8761"
            - name: INSTANCE_HOSTNAME
              value: ms-evaluation
---
apiVersion: v1
kind: Service
metadata:
  name: ms-calculation
  labels:
    app: ms-calculation-deployment
spec:
  clusterIP: None
  selector:
    app: ms-calculation-pod
  ports:
    - protocol: TCP
      port: 8080 # Puerto dummy para no afectar puertos dinámicos
      targetPort: 8080