apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-tracking
  labels:
    app: ms-tracking-deployment
spec:
  selector:
    matchLabels:
      app: ms-tracking-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-tracking-pod
    spec:
      containers:
        - name: ms-tracking
          image: nicolassepulvedab/ms-tracking-service
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_TRACKING
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_TRACKING
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_TRACKING
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_TRACKING
            - name: CONFIG_SERVER_HOST
              value: "config-service-service"
            - name: EUREKA_HOST
              value: "eureka-service-service"
            - name: EUREKA_PORT
              value: "8761"
            - name: INSTANCE_HOSTNAME
              value: ms-tracking
---
apiVersion: v1
kind: Service
metadata:
  name: ms-tracking
  labels:
    app: ms-tracking-deployment
spec:
  clusterIP: None
  selector:
    app: ms-tracking-pod
  ports:
    - protocol: TCP
      port: 8080 # Puerto dummy para no afectar puertos dinámicos
      targetPort: 8080