server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DBNAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}