server:
  port: ${SERVER_PORT:8761}
spring:
  config:
    activate:
      on-profile: eureka-service
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url: 
      default-zone: http://${INSTANCE_HOSTNAME}:${SERVER_PORT}/eureka/
  instance:
    prefer-ip-address: false
    hostname: ${INSTANCE_HOSTNAME}