# Configuración común
server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DBNAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

# Configuración específica para dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_DBNAME}

# Configuración específica para prod
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DBNAME}
