server:
  port: ${PORT:${SERVER_PORT:0}}
feign:
  discovery:
    enabled: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prestabanco-evaluations
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}