server:
  port: 8082
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-client-service
          uri: lb://ms-client-service
          predicates:
            - Path=/api/v1/clients/**
            - Path=/api/v1/executives/**
            - Path=/api/auth/**
        - id: ms-credit-service
          uri: lb://ms-credit-service
          predicates:
            - Path=/api/v1/credits/**
        - id: ms-document-service
          uri: lb://ms-document-service
          predicates:
            - Path=/api/v1/documents/**
        - id: ms-evaluation-service
          uri: lb://ms-evaluation-service
          predicates:
            - Path=/api/v1/evals/**
        - id: ms-creditcalculate-service
          uri: lb://ms-creditcalculate-service
          predicates:
            - Path=/api/v1/calculations/**
        - id: ms-tracking-service
          uri: lb://ms-tracking-service
          predicates:
            - Path=/api/v1/tracking/**