server:
  port: 8082
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
  instance:
    hostname: ${INSTANCE_HOSTNAME}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*' #acá el front
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-user-service
          uri: lb://USERS
          predicates:
            - Path=/api/v1/clients/**,/api/v1/executives/**,/api/auth/**
        - id: ms-credit-service
          uri: lb://CREDITS
          predicates:
            - Path=/api/v1/credits/**
        - id: ms-document-service
          uri: lb://DOCUMENTS
          predicates:
            - Path=/api/v1/documents/**
        - id: ms-evaluation-service
          uri: lb://EVALUATION
          predicates:
            - Path=/api/v1/evals/**
        - id: ms-calculation-service
          uri: lb://CALCULATION
          predicates:
            - Path=/api/v1/calculations/**
        - id: ms-tracking-service
          uri: lb://TRACKING
          predicates:
            - Path=/api/v1/tracking/**