server:
  port: 8082
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-client-service
          uri: lb://ms-client-service
          predicates:
            - Path=/client/**
        - id: ms-credit-service
          uri: lb://ms-credit-service
          predicates:
            - Path=/credit/**
        - id: ms-document-service
          uri: lb://ms-document-service
          predicates:
            - Path=/document/**
        - id: ms-evaluation-service
          uri: lb://ms-evaluation-service
          predicates:
            - Path=/evaluation/**
        - id: ms-creditcalculate-service
          uri: lb://ms-creditcalculate-service
          predicates:
            - Path=/creditcalculate/**
        - id: ms-tracking-service
          uri: lb://ms-tracking-service
          predicates:
            - Path=/tracking/**                                                