logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.filter: TRACE
    org.springframework.cloud.gateway.handler: TRACE
    reactor.netty.http.server: TRACE
