apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-evaluations-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db-evaluations-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-evaluations-pvc
  labels:
    app: postgres
    tier: database
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-evaluations
  labels:
    app: db-evaluations-deployment
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-evaluations-pod
  template:
    metadata:
      labels:
        app: db-evaluations-pod
        tier: database
    spec:
      containers:
        - name: db-evaluations
          image: postgres:16
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_EVALUATIONS
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_EVALUATIONS
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-evaluations-data
            - mountPath: /docker-entrypoint-initdb.d
              name: init-scripts
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - |
                    export PGPASSWORD="$POSTGRES_PASSWORD"
                    until pg_isready -U "$POSTGRES_USER" -h "localhost"; do
                      echo "$(date): Esperando a que PostgreSQL esté listo..."
                      sleep 2
                    done
                    psql -U "$POSTGRES_USER" -h localhost -d postgres -f /docker-entrypoint-initdb.d/init.sql || true    
      volumes:
        - name: db-evaluations-data
          persistentVolumeClaim:
            claimName: db-evaluations-pvc
        - name: init-scripts
          configMap:
            name: prestabanco-evaluations-init-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: db-evaluations-service
  labels:
    app: db-evaluations-service
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: db-evaluations-pod
    tier: database
  type: LoadBalancer