apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deployment
  labels:
    app: gateway-service-deployment
spec:
  selector:
    matchLabels:
      app: gateway-service-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-service-pod
    spec:
      containers:
        - name: gateway-service
          image: nicolassepulvedab/gateway-service
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service-service
  labels:
    app: gateway-service-service
spec:
  selector:
    app: gateway-service-deployment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer