apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-tracking
  labels:
    app: ms-tracking-deployment
spec:
  selector:
    matchLabels:
      app: ms-tracking-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-tracking-pod
    spec:
      containers:
        - name: ms-tracking
          image: nicolassepulvedab/ms-tracking-service
          ports:
            - containerPort: 8094
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_TRACKING
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_TRACKING
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_TRACKING
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_USER_TRACKING
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_PASSWORD_TRACKING
