apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-user
  labels:
    app: ms-user-deployment
spec:
  selector:
    matchLabels:
      app: ms-user-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-user-pod
    spec:
      containers:
        - name: ms-user
          image: nicolassepulvedab/ms-user-service
          ports:
            - containerPort: 8095
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_USERS
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_USERS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_USER_USERS
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_PASSWORD_USERS
