apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  DB_HOST_CALCULATIONS: db-calculations-service
  DB_DBNAME_CALCULATIONS: prestabanco_calculations
  DB_HOST_CREDITS: db-credits-service
  DB_DBNAME_CREDITS: prestabanco_credits
  DB_HOST_DOCUMENTS: db-documents-service
  DB_DBNAME_DOCUMENTS: prestabanco_documents
  DB_HOST_EVALUATIONS: db-evaluations-service
  DB_DBNAME_EVALUATIONS: prestabanco_evaluations
  DB_HOST_TRACKING: db-tracking-service
  DB_DBNAME_TRACKING: prestabanco_tracking
  DB_HOST_USERS: db-users-service
  DB_DBNAME_USERS: prestabanco_users
  DB_PORT: "5432"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prestabanco-calculations-init-scripts
data:
  init.sql: |
    SELECT 'CREATE DATABASE prestabanco_calculations' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'prestabanco_calculations')\gexec
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prestabanco-credits-init-scripts
data:
  init.sql: |
    SELECT 'CREATE DATABASE prestabanco_credits' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'prestabanco_credits')\gexec
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prestabanco-documents-init-scripts
data:
  init.sql: |
    SELECT 'CREATE DATABASE prestabanco_documents' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'prestabanco_documents')\gexec
---    
apiVersion: v1
kind: ConfigMap
metadata:
  name: prestabanco-evaluations-init-scripts
data:
  init.sql: |
    SELECT 'CREATE DATABASE prestabanco_evaluations' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'prestabanco_evaluations')\gexec
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prestabanco-tracking-init-scripts
data:
  init.sql: |
    SELECT 'CREATE DATABASE prestabanco_tracking' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'prestabanco_tracking')\gexec
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prestabanco-users-init-scripts
data:
  init.sql: |
    SELECT 'CREATE DATABASE prestabanco_users' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'prestabanco_users')\gexec 