apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  DB_HOST_CALCULATIONS: prestabanco-calculations-service
  DB_DBNAME_CALCULATIONS: prestabanco-calculations
  DB_HOST_CREDITS: prestabanco-credits-service
  DB_DBNAME_CREDITS: prestabanco-credits
  DB_HOST_DOCUMENTS: prestabanco-documents-service
  DB_DBNAME_DOCUMENTS: prestabanco-documents
  DB_HOST_EVALUATIONS: prestabanco-evaluations-service
  DB_DBNAME_EVALUATIONS: prestabanco-evaluations
  DB_HOST_TRACKING: prestabanco-tracking-service
  DB_DBNAME_TRACKING: prestabanco-tracking
  DB_HOST_USERS: prestabanco-users-service
  DB_DBNAME_USERS: prestabanco-users
  DB_PORT: "5432"