apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  DB_HOST_CALCULATION: orders-db-service
  DB_PORT_CALCULATION: "5432"
  DB_DBNAME_CALCULATION: orders-db
  DB_HOST_PRODUCTS: products-db-service
  DB_PORT_PRODUCTS: "5433"
  DB_DBNAME_PRODUCTS: products-db
