package enums;

public enum DocumentType {
    INCOMECERTIFY,
    VALUATIONCERTIFY,
    CREDITREPORT,
    FIRSTHOUSEDEED,
    FINANCIALSTATUSREPORT,
    BUSINESSPLAN,
    REMODELINGBUDGET,
    UPDATEDVALUATIONCERTIFY
}
