server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/nico-s-b/prestabanco-microservices
          search-paths: config-data
  application:
    name: config-service
