package com.example.common_utils.enums;

public enum DocumentType {
    INCOMECERTIFY,
    VALUATIONCERTIFY,
    CREDITREPORT,
    FIRSTHOUSEDEED,
    FINANCIALSTATUSREPORT,
    BUSINESSPLAN,
    REMODELINGBUDGET,
    UPDATEDVALUATIONCERTIFY,
    EXTRADOCUMENTATION
}
